### ISSUE TITLE
请问可以提供一下用法流程吗？不太清楚怎么做

### ISSUE THREAD

**Issue by SJLMax** [excing/chatgpt#2]

**Comment by excing** [comment]
Fork 这个项目到你的仓库，然后开启你的仓库的 Pages 即可使用了。

这个是我的仓库 Pages 链接：<https://excing.github.io/chatgpt/>

不知道你用过 github pages 没有？这里默认你会使用。

打开 pages 站点，填写 Domain，默认是 openai api 的官方链接：<https://api.openai.com>，然后填写你的 API Key，这个你要从你的 openai 个人设置页获取，然后点击 "Update" 按钮。

这样就可以使用了。

**Comment by SJLMax** [comment]
确认科学上网了，请问出现报错是啥原因呐？TypeError: Failed to fetch

**Comment by excing** [comment]
方便提供一个截图吗？API Key 打码。还有控制台的输出。

**Comment by SJLMax** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/56500650/226293143-6631987b-2395-4351-835b-427508e59102.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/56500650/226293277-d5b553d7-11c1-4163-ad61-bc68b72e1879.png">
这样可以吗？

**Comment by excing** [comment]
虽然但是，你可以把 "Text to speech" 选项关掉，应该可以看到更详细的错误提示。

不过大概是网络原因吧，你可以在浏览器里请求访问填写的 Domain，就是你填写的：<https://api.openai.com>，如果出现下面的内容，说明你的网络是正常的，如果出现无法访问，那么就是网络问题。

![image](https://user-images.githubusercontent.com/11867809/226320980-5b8d2833-f2e7-4a6a-997b-1c1a15070925.png)

**Comment by donething** [comment]
我fork后这样弄，访问提示 404
通过 https://donething.github.io/ 还是 https://donething.github.io/chatgpt 都是 404。。

![屏幕截图 2023-04-17 100551](https://user-images.githubusercontent.com/11867885/232361191-97e7acaa-ba7f-473b-9125-54fa09be4e92.png)
