### ISSUE TITLE
用了一段时间后的一些需求

### ISSUE THREAD

**Issue by xzxz520cs** [excing/chatgpt#5]
1.想要能一键删除历史记录，我现在历史记录太多已经要等两秒才能点开了。
2.历史记录里过去的对话很难找，希望能把特定的对话命个名单独收藏起来。
3.历史记录里的文字如果有HTML会被可视化。
4.聊了很长之后要开新的对话要翻很长到页面最上，希望能优化一下UI.

**Comment by excing** [comment]
已解决
